### ISSUE TITLE
SAP Systems - Filters -SID doesn't work or works only with big delay

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#545]
trento server v0.6.0
deployed on QA Server: http://20.67.108.123

Open http://20.67.108.123/sapsystems (It might take very long time or show 'Bad Gateway', known issue)
To filter by SID, for example NWD, it doesn't display a new list at once or it takes very long time(minutes) to show the changes if it works.  This makes the filter function nearly useless.

See screenshots.

1.

![sap-system-filter-sid-1](https://user-images.githubusercontent.com/4113246/145001549-b3f4e021-2cbc-46dc-9b84-c4d94a86724d.jpg)

2.

![sap-system-filter-sid-2](https://user-images.githubusercontent.com/4113246/145001586-a1f79d9a-6a43-4146-a37c-e5f6f38a7f80.jpg)

3.

![sap-system-filter-sid-3](https://user-images.githubusercontent.com/4113246/145001613-d2d09004-5497-4f0b-b6c5-13d4efc97092.jpg)

**Comment by fabriziosestito** [comment]
Fixed by #538

**Comment by abravosuse** [comment]
v0.7.0: issue persists (I don't get a bad gateway error but view takes a long time to reload sometimes after setting filter @fabriziosestito @stefanotorresi should we reopen this issue or create a new one?
