### ISSUE TITLE
Bad Gateway or always get an error message about fetching checks date for hana_cluster

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#606]
Testing 3rd round
Server version: v0.6.0+git.dev293.1639737346.f1029ae

Try to open link of hana_cluster:

http://20.126.10.94/clusters/a4c04cc9d12431bf9357937d6c0a02bd
I get very often issue with 'Bad Gateway'  or an error displayed. The page got loaded after Re-try.
I don't think this provides a good user experience with pop-up message here. 

![image](https://user-images.githubusercontent.com/4113246/146562778-57c3192a-e429-4d01-b66c-e18c9bf766c8.png)

**Comment by fabriziosestito** [comment]
@Zaoliang please update the web version to the new rolling version (`b425ce9`). The new rolling version should resolve the error message.

**Comment by abravosuse** [comment]
@fabriziosestito we cannot update the release in the middle of a testing round because that forces us to restart from the scratch. We did it this morning with the big performance issue because we had barely started the testing and it was almost impossible to work with the console. 
Let us please finish this round with the version indicated by Zaoliang in the description and we will pay special attention to this particular issue in the next round. Let's keep the issue open until then.

**Comment by abravosuse** [comment]
Hello @fabriziosestito: we have updated to v0.7.0 and I'm afraid the issue persists. I'm getting both the OH NOES pop-up window and the Bad Gateway message when working with clusters view.
![image](https://user-images.githubusercontent.com/91731013/146683609-db0d44ed-778d-4a10-8971-8b515be37065.png)

**Comment by fabriziosestito** [comment]
@abravosuse I am afraid those are two independent issues. The Bad Gateway is due ARA poor performances and it is being worked on as a part of the ARA removal task.
The check settings loading error was caused by a bug in the web framework we use and it should be solved by #608
